spring:
  application:
        name: exercise
  threads:
    virtual:
      enabled: true
  jackson:
    default-property-inclusion: non_absent
  docker:
    compose:
      lifecycle-management: start_and_stop
      stop:
        command: down
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        cache:
          region.factory_class: jcache
          use_query_cache: true
          use_second_level_cache: true

        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            default_cache_concurrency_strategy: read-write
            missing_cache_strategy: create
    defer-datasource-initialization: false
  cache:
    cache-names: player, tournament, player_tournament,

  sql:
    init:
      mode: always

logging:
  level:
        org.hibernate.SQL: trace
        org.hibernate.orm.jdbc.bind: trace
        org.hibernate.stat: trace
        org.hibernate.SQL_SLOW: trace
        org.hibernate.cache: trace

        liquibase:
            change-log: trace
            logger: trace
            logging: trace
            sql: trace